# Generated by Django 5.2.4 on 2025-07-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=100, unique_for_date="publish"),
        ),
    ]
